### ISSUE TITLE
add "svg_only" to "plantuml_output_format" configuration

### ISSUE THREAD

**Issue by melvinvermeeren** [sphinx-contrib/plantuml#16] opened 2018-07-20 23:58 UTC
Currently I am working on a project with a lot of documentation with PlantUML diagrams. The CI builds and deploys a fresh documentation build for every commit pushed on this project. Many more diagrams will be added in the future.

PNG only
`make doc  91,95s user 8,95s system 474% cpu 21,250 total`

SVG+PNG fallback
`make doc  167,16s user 15,93s system 512% cpu 35,725 total`

On the CI server the total time for SVG+PNG fallback is currently 112 seconds, it is not as fast as my desktop. Building only SVG is acceptable for our project and would speed up build time a lot.

I think this is easy to add, I will try to submit a patch tomorrow.

**Comment by yuja** [comment] 2018-07-21 00:57
Sounds good. This is a duplicate of #7.

**Comment by melvinvermeeren** [comment] 2018-07-21 10:41
I do not think this is a duplicate. This issue is about adding a config to render only SVG *without* PNG fallback, to save CPU time when building. #7 is (I think) about using `<img/>` instead of `<object/>` for svg images.

Anyway, I will do some hacking today, you may find some PR show up soon. :)

**Comment by melvinvermeeren** [comment] 2018-07-21 12:37
See PR #17

**Comment by yuja** [comment] 2018-07-22 04:35
Ah, good catch, thanks.

**Closed** 2018-07-22 04:57 UTC
